jobs:
  fast_finish: true
  include:
    - stage: build
      install: docker build --tag ci .ci
      script: docker run --init --rm -e TRAVIS_TAG --mount type=bind,source="${PWD}",target=/app ci
      os: linux
      dist: xenial
      language: generic
      services:
        - docker

before_deploy: sha256sum artifacts/*/*

deploy:
  provider: releases
  api_key:
    secure: "TzuRIQ3mUqlkPnb9TuPZUw+HohBx/AADTjMZt2M44ZRA401SD6sIqgb2O5IlvTL52gLi49fMCC3Rqia695GQgfOUA40tGlOd9EN9Q26sCzGIf1Xw3AEDVqDOkKfIxkAXKkmZnFIXPauUSjD5vg2//OHMAVzCxftfQ3iECXDx7du4DMFkeG+6BVL897mKas1lDOZqiQHHD2Uzx/FnQCTnpLEjRaxLD4MaLFD9HH7Fh4DeqFxRJJWt73CuqrPKkjQnLUFOq0qW+kfMHYKqn4Ba8dQiLChRpFD3+mB5mbE28fDw3M05SHadIfWBHihT0ihwZJ823pIrKvoirF6V/fi0hA/zZ7BZSrYywCK/Vej1sDfJucW+4fi9PNpk55Z002jccy60pST7SdRy26Tm/fb8QEYHdWREkUy3FgnTfdImfBnz/0ScicLXZXA/+xcxPGD6Q+vbIw501+9cFerzreDiiL6wBBnu7mXZYP5QVIByC/y0P/N0Ov6CSqTYwL6wNdDQorsIEa2Lova40gruutjk4n/vfTGEi8tcUFBUJC/fG3fxB8HGAxsm0Co22u0GiZgMmC66UpuvLI1QkqA4+TCWO4WJYaBNm0ylyqUCZWyMIqwEHEKO5Ehzgk7Fx2QJD1kaVSfFy5ts3921pum9cHhsuovZlSgg8DZomUBm/TBGQDo="
  draft: true
  file: artifacts/*/*
  file_glob: true
  overwrite: true
  skip_cleanup: true
  body: "Download and install the extension from the [extension store](https://github.com/dessant/youtube-autoplay#readme) of your browser.<br>Learn more about this release from the [changelog](https://github.com/dessant/youtube-autoplay/blob/master/CHANGELOG.md#changelog).<br><br>The assets listed below are not for general use."
  on:
    tags: true
